### ISSUE TITLE
Make command is failing 

### ISSUE THREAD

**Issue by srkolli** [target/attack-navigator-docker#4]
**Describe the bug**
The make command in Readme for building the docker image are not working 

Below is the output
[root@centos73_v182101_01 attack-navigator-docker]# make
docker pull node:"10-slim"
Trying to pull repository docker.io/library/node ...
10-slim: Pulling from docker.io/library/node
Digest: sha256:115c3f43131bee55da9f240a3e3a74bb125a3efe3a10a55196a08d0ba2ee1a50
Status: Image is up to date for docker.io/node:10-slim
docker pull nginx:stable-alpine
Trying to pull repository docker.io/library/nginx ...
stable-alpine: Pulling from docker.io/library/nginx
Digest: sha256:270bea203d2fc3743fb9ce0193325e188b7e6233043487e3d3cf117ea4d3f337
Status: Image is up to date for docker.io/nginx:stable-alpine
git submodule init
git submodule update
docker run -it --rm -v `pwd`/attack-navigator:/attack-navigator node:"10-slim" /bin/sh -c 'cd /attack-navigator/nav-app && npm install && npm run build'
Error: EACCES: permission denied, scandir '/attack-navigator/nav-app'
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:112:20
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'loaded' of undefined
    at process.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:40:18)
    at process.emit (events.js:198:13)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
make: *** [build] Error 7
[root@centos73_v182101_01 attack-navigator-docker]#

CentOS Linux release 7.6.1810
Docker version 1.13.1, build 7f2769b/1.13.1

**Comment by srkolli** [comment]
Thank you. I used this link to resolve the issue https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
